@startuml
participant "Domain Interface"
participant "Belief Update"
database "Contracts, Policies, Other Beliefs"
participant "Policy Engine"
participant "Contract Engine"
participant "Goal Maintenance"
database "Goal Set"
participant "Event Treating Engine"
participant "Plan Engine"
database "Plan Library"
database "Intention Set"
participant "Execution Engine"
participant "Communication Interface"

"Domain Interface" -> "Event Treating Engine" ++: Make observations
"Event Treating Engine" ->> "Belief Update" ++ : Send ExtE
"Belief Update" -> "Contracts, Policies, Other Beliefs" -- : Update beliefs

"Event Treating Engine" ->> "Policy Engine" ++ : Send ExtE
"Policy Engine" -> "Policy Engine" : Evaluate policies
"Policy Engine" ->> "Event Treating Engine" -- : Send POblE

"Event Treating Engine" ->> "Contract Engine" ++ : Send ExtE
"Contract Engine" -> "Contract Engine" : Evaluate contracts
"Contract Engine" ->> "Event Treating Engine" -- : Send COblE, DesE

"Event Treating Engine" ->> "Goal Maintenance": Send POblE, COblE, DesE
deactivate "Event Treating Engine"
activate "Goal Maintenance"

"Goal Maintenance" -> "Goal Maintenance" : "Treats with conflicts among them"
"Goal Maintenance" -> "Goal Set" -- : Update goals

activate "Plan Engine"
loop forever
    "Plan Engine" -> "Goal Set" : Query for goal
    "Plan Engine" <-- "Goal Set" : Goal
    "Plan Engine" -> "Plan Library" : Query for plan
    "Plan Engine" <-- "Plan Library" : Plan
    "Plan Engine" -> "Intention Set" : Push plan on stack
end

loop forever
    "Plan Engine" -> "Intention Set" : Query for intention stacks
    "Plan Engine" <-- "Intention Set" : Intention stack
    "Plan Engine" -> "Plan Engine" : Select topmost plan
    "Plan Engine" ->> "Execution Engine" ++ : Send next step in plan
end
deactivate "Plan Engine"

alt Step is a domain action
    "Execution Engine" -> "Execution Engine" : Perform action
else Step is a goal or action to be done by an external agent
    "Execution Engine" -> "Execution Engine" : Encapsulate step in CooperationInfo event
    "Execution Engine" ->> "Event Treating Engine" ++ : Send CooperationInfo
    "Event Treating Engine" ->> "Communication Interface" -- : Send CooperationInfo
else Step is a subgoal
    "Execution Engine" -> "Goal Set" : Suspend current plan
    "Execution Engine" -> "Execution Engine" : Encapsulate subgoal into DesE
    "Execution Engine" ->> "Event Treating Engine" : Send DesE
end
deactivate "Execution Engine"

@enduml
