terminal:
  image: ubuntu:20.04

  variables:
    RAILS_ENV: test
    NODE_ENV: test

  services:
    # See https://docs.gitlab.com/ee/user/project/web_ide/#file-syncing-to-web-terminal
    - name: registry.gitlab.com/gitlab-org/webide-file-sync:latest
      alias: webide-file-sync
      entrypoint: ["/bin/sh"]
      command: ["-c", "sleep 5 && ./webide-file-sync -project-dir $CI_PROJECT_DIR"]
      ports:
        # The `webide-file-sync` executable defaults to port 3000.
        - number: 3000
