gantt
	title Timeline
	dateFormat  YYYY-MM-DD

	section Academic calendar
		Fall semester				: fall_semester, 2020-08-17, 2020-12-08
		Christmas break				: christmas_break, 2020-12-09, 2021-01-23
		%% J-term						: j_term, 2021-01-02, 2021-01-23
		Spring semester				: spring_semester, 2021-01-25, 2021-05-14

	section Research
		Create examples				: create_examples, 2020-08-24, 3w
		Update AIA to use clingo	: update_aia, after create_examples, 5w
		Implement AIA/AOPL			: implement_aia_aopl, after update_aia, 4w
		Apply AIA/AOPL to examples	: apply_aia_aopl, after implement_aia_aopl, 2w
		Apply AIA/AOPL to examples	: apply_aia_aopl, after christmas_break, 2w

	section Write-up
		Write thesis				: thesis, after create_examples, 2020-12-01
		Write thesis				: thesis, after christmas_break, 2021-04-01
		Submit to thesis committee	: committee_submission, 2021-04-01, 1d
		Prepare for Thesis Defense	: after committee_submission, 7d
		Thesis Defense				: crit, defense, 2021-04-10, 1d
		Apply final edits			: after defense, 2021-04-17
		Submit to Graduate school	: crit, final_submission, 2021-04-17, 1d
